[project]
name = "submission-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.1",
    "pika>=1.3.2",
    "psycopg2-binary>=2.9.11",
    "sqlmodel>=0.0.32",
    "uvicorn>=0.40.0",
]
